### ISSUE TITLE
Devolutiva do Exercício

### ISSUE THREAD

**Issue by rmazevedo** [felipesampaio91/projetoPipoBackend#1]
Oi Felipe! Obrigado pela dedicação no nosso exercício. Para conseguirmos avaliar melhor gostaríamos de sugerir alguns pontos.

E sinta-se à vontade para priorizar o que achar que faz sentido e se houver dúvidas não hesite em nos mandar.

-**Documentação**: sentimos falta dos passos para rodar o projeto, rodar testes, o que precisamos instalar, ferramentas que utilizou e como criar o banco.
-**Testes**: você comentou que não conseguiu finalizar o TDD, ficamos na dúvida o que significa, porque o TDD é uma metodologia. Se precisar de mais tempo para para finalizar os testes, não consideramos o tempo de resolução do exercício na avaliação, então pode ficar à vontade.
-**Comentários**: poderia nos contar um pouco mais sobre quais hipóteses você assumiu, por exemplo, quem seria o usuário? Se quiser comentar também quais motivações de utilizar .NET ou a arquitetura que definiu.

**Comment by felipesampaio91** [comment]
Olá! Documentação refatorada e desenvolvimento finalizado. Qualquer dúvida sigo à disposição.
